In [1]:
import torch
import math

In [4]:
emb = torch.arange(0, 128, step=2)
print(emb)

tensor([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,
         56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
         84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104, 106, 108, 110,
        112, 114, 116, 118, 120, 122, 124, 126])


In [5]:
emb = emb / 128
print(emb)

tensor([0.0000, 0.0156, 0.0312, 0.0469, 0.0625, 0.0781, 0.0938, 0.1094, 0.1250,
        0.1406, 0.1562, 0.1719, 0.1875, 0.2031, 0.2188, 0.2344, 0.2500, 0.2656,
        0.2812, 0.2969, 0.3125, 0.3281, 0.3438, 0.3594, 0.3750, 0.3906, 0.4062,
        0.4219, 0.4375, 0.4531, 0.4688, 0.4844, 0.5000, 0.5156, 0.5312, 0.5469,
        0.5625, 0.5781, 0.5938, 0.6094, 0.6250, 0.6406, 0.6562, 0.6719, 0.6875,
        0.7031, 0.7188, 0.7344, 0.7500, 0.7656, 0.7812, 0.7969, 0.8125, 0.8281,
        0.8438, 0.8594, 0.8750, 0.8906, 0.9062, 0.9219, 0.9375, 0.9531, 0.9688,
        0.9844])


In [6]:
emb = emb * math.log(10000)
print(emb)

tensor([0.0000, 0.1439, 0.2878, 0.4317, 0.5756, 0.7196, 0.8635, 1.0074, 1.1513,
        1.2952, 1.4391, 1.5830, 1.7269, 1.8709, 2.0148, 2.1587, 2.3026, 2.4465,
        2.5904, 2.7343, 2.8782, 3.0221, 3.1661, 3.3100, 3.4539, 3.5978, 3.7417,
        3.8856, 4.0295, 4.1734, 4.3173, 4.4613, 4.6052, 4.7491, 4.8930, 5.0369,
        5.1808, 5.3247, 5.4686, 5.6126, 5.7565, 5.9004, 6.0443, 6.1882, 6.3321,
        6.4760, 6.6199, 6.7638, 6.9078, 7.0517, 7.1956, 7.3395, 7.4834, 7.6273,
        7.7712, 7.9151, 8.0590, 8.2030, 8.3469, 8.4908, 8.6347, 8.7786, 8.9225,
        9.0664])


In [8]:
mm = math.log(10000)
print(mm)

9.210340371976184


In [9]:
emb

tensor([0.0000, 0.1439, 0.2878, 0.4317, 0.5756, 0.7196, 0.8635, 1.0074, 1.1513,
        1.2952, 1.4391, 1.5830, 1.7269, 1.8709, 2.0148, 2.1587, 2.3026, 2.4465,
        2.5904, 2.7343, 2.8782, 3.0221, 3.1661, 3.3100, 3.4539, 3.5978, 3.7417,
        3.8856, 4.0295, 4.1734, 4.3173, 4.4613, 4.6052, 4.7491, 4.8930, 5.0369,
        5.1808, 5.3247, 5.4686, 5.6126, 5.7565, 5.9004, 6.0443, 6.1882, 6.3321,
        6.4760, 6.6199, 6.7638, 6.9078, 7.0517, 7.1956, 7.3395, 7.4834, 7.6273,
        7.7712, 7.9151, 8.0590, 8.2030, 8.3469, 8.4908, 8.6347, 8.7786, 8.9225,
        9.0664])

In [13]:
emb[None,:].size()

torch.Size([1, 64])

In [12]:
emb.size()

torch.Size([64])

In [14]:
rec_1 = torch.randn([3,4])
print(rec_1)
rec_2 = torch.randn([3,4])
print(rec_2)
rec_3 = torch.stack([rec_1, rec_2], dim=-1)
print(rec_3)

tensor([[ 1.4561, -0.4390, -0.4868,  0.7989],
        [-0.1961,  0.8032, -0.7547,  0.1078],
        [ 0.2671, -0.8970,  1.0189,  1.2110]])
tensor([[-1.9422,  1.4750, -1.5583, -0.3961],
        [ 0.8543,  0.6715,  0.3265,  0.3241],
        [ 0.5794, -0.4229,  0.0770,  1.0668]])
tensor([[[ 1.4561, -1.9422],
         [-0.4390,  1.4750],
         [-0.4868, -1.5583],
         [ 0.7989, -0.3961]],

        [[-0.1961,  0.8543],
         [ 0.8032,  0.6715],
         [-0.7547,  0.3265],
         [ 0.1078,  0.3241]],

        [[ 0.2671,  0.5794],
         [-0.8970, -0.4229],
         [ 1.0189,  0.0770],
         [ 1.2110,  1.0668]]])


In [16]:
rec_4 = rec_3.view(3, 8)
print(rec_4)

tensor([[ 1.4561, -1.9422, -0.4390,  1.4750, -0.4868, -1.5583,  0.7989, -0.3961],
        [-0.1961,  0.8543,  0.8032,  0.6715, -0.7547,  0.3265,  0.1078,  0.3241],
        [ 0.2671,  0.5794, -0.8970, -0.4229,  1.0189,  0.0770,  1.2110,  1.0668]])
