In [1]:
import torch

/opt/conda/envs/ma/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


计算两个tensor的矩阵乘法，torch.bmm(a,b),tensor a 的size为(b,h,w),tensor b的size为(b,w,m) 也就是说两个tensor的第一维是相等的，然后第一个数组的第三维和第二个数组的第二维度要求一样，对于剩下的则不做要求，输出维度 （b,h,m）

In [2]:
c = torch.rand((2,5))
print(c)

tensor([[0.8581, 0.4390, 0.8532, 0.2698, 0.8367],
        [0.7298, 0.4838, 0.5234, 0.7774, 0.5474]])


In [3]:
c.size()

torch.Size([2, 5])

In [4]:
c2 = torch.rand(2,5)

In [5]:
print(c2)

tensor([[0.1716, 0.6440, 0.6177, 0.2560, 0.4287],
        [0.7752, 0.1686, 0.5261, 0.0840, 0.5642]])


In [6]:
c2.size()

torch.Size([2, 5])

In [7]:
d =  torch.reshape(c,(5,2))

In [8]:
print(d)

tensor([[0.8581, 0.4390],
        [0.8532, 0.2698],
        [0.8367, 0.7298],
        [0.4838, 0.5234],
        [0.7774, 0.5474]])


In [9]:
d.size()

torch.Size([5, 2])

In [10]:
e = torch.bmm(c,d)
# 我们发现，当维度为2时，会出现报错的情况

RuntimeError: batch1 must be a 3D tensor

In [11]:
cc = torch.randn(1,2,2,5)
print(cc)

tensor([[[[ 0.2729,  0.2173, -0.1271,  0.7439,  1.2944],
          [-0.3903,  1.4724, -0.3173,  0.1969,  0.0870]],

         [[ 0.3448, -0.5552, -0.0229,  0.0683, -0.4991],
          [ 0.1647, -1.5861,  0.8731, -2.6176, -0.6225]]]])


In [12]:
cc.size()

torch.Size([1, 2, 2, 5])

In [13]:
dd = torch.randn(1,2,5,2)
print(dd)
dd.size()

tensor([[[[ 0.4481, -0.6019],
          [ 0.8865, -0.2343],
          [ 0.3345,  0.0251],
          [ 0.9215, -0.7081],
          [ 0.7945,  0.2403]],

         [[-1.7657, -1.1692],
          [-1.0709,  0.6174],
          [ 0.0112, -0.8930],
          [ 0.2131, -1.0343],
          [ 1.4137, -0.1128]]]])


torch.Size([1, 2, 5, 2])

In [14]:
ee = torch.bmm(c,d)
# 我们发现，维度为4的时候也会报错

RuntimeError: batch1 must be a 3D tensor

In [15]:
ccc = torch.randn(2,2,5)
print(ccc)
ccc.size()

tensor([[[-0.5698, -0.8657, -1.2538,  0.7192, -1.9031],
         [-1.4291,  1.0079,  1.1709, -0.4838, -0.3506]],

        [[-0.1370, -4.2803,  1.3814, -0.3980,  0.3010],
         [ 1.2918, -0.0163,  0.6664, -1.5555,  0.6580]]])


torch.Size([2, 2, 5])

In [16]:
ddd = torch.randn(2,5,2)
print(ddd)
ddd.size()

tensor([[[-0.3537,  0.9236],
         [-0.1102, -0.8424],
         [ 0.4779, -0.5336],
         [ 0.2603, -1.7673],
         [-1.3040, -0.6659]],

        [[ 1.5417, -0.9639],
         [ 1.0685,  1.7429],
         [-0.8761,  0.0682],
         [ 0.4349, -0.8468],
         [ 2.0272, -0.2994]]])


torch.Size([2, 5, 2])

In [17]:
eee = torch.bmm(ccc, ddd)

In [18]:
eee.size()

torch.Size([2, 2, 2])