In [1]:
import torch
import torch.nn as nn

In [38]:
target = torch.randint(2, (3,4,1))
print(target)

tensor([[[0],
         [0],
         [0],
         [0]],

        [[0],
         [1],
         [0],
         [0]],

        [[0],
         [1],
         [1],
         [1]]])


In [33]:
input =  torch.rand(3,4,1)
print(input)

tensor([[[0.1736],
         [0.2487],
         [0.7978],
         [0.8876]],

        [[0.4897],
         [0.2978],
         [0.4485],
         [0.9680]],

        [[0.5281],
         [0.0368],
         [0.8819],
         [0.5093]]])


In [9]:
from torch import distributions as dist

In [34]:
input_bnl = dist.Bernoulli(probs=input)

In [35]:
input_bnl.probs

tensor([[[0.1736],
         [0.2487],
         [0.7978],
         [0.8876]],

        [[0.4897],
         [0.2978],
         [0.4485],
         [0.9680]],

        [[0.5281],
         [0.0368],
         [0.8819],
         [0.5093]]])

In [36]:
input_bnl.logits

tensor([[[-1.5604],
         [-1.1058],
         [ 1.3724],
         [ 2.0665]],

        [[-0.0414],
         [-0.8577],
         [-0.2065],
         [ 3.4093]],

        [[ 0.1125],
         [-3.2636],
         [ 2.0108],
         [ 0.0370]]])

In [15]:
import torch.nn.functional as F

In [39]:
loss = F.binary_cross_entropy_with_logits(input_bnl.logits, target.float(), reduction='none')
print(loss)

tensor([[[0.1907],
         [0.2859],
         [1.5984],
         [2.1857]],

        [[0.6727],
         [1.2113],
         [0.5952],
         [3.4418]],

        [[0.7510],
         [3.3012],
         [0.1256],
         [0.6748]]])


In [40]:
loss_sum =  loss.sum(-1)
print(loss_sum)
loss_mean = loss_sum.mean()
print(loss_mean)

tensor([[0.1907, 0.2859, 1.5984, 2.1857],
        [0.6727, 1.2113, 0.5952, 3.4418],
        [0.7510, 3.3012, 0.1256, 0.6748]])
tensor(1.2529)


In [41]:
loss_avg = loss.mean()
print(loss_avg)

tensor(1.2529)


In [27]:
torch.mean(target*(input_bnl.probs > 0.5).float() + (1-target)*(input_bnl.probs<=0.5).float())

tensor(0.5333)

In [26]:
a1 = target*(input_bnl.probs > 0.5).float()
print(a1)
print(a1.shape)

tensor([[[0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 0., 1., 0.]],

        [[0., 0., 0., 0., 1.],
         [1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 1., 0., 1., 0.],
         [0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 1.],
         [0., 0., 1., 0., 1.]]])
torch.Size([3, 4, 5])


In [42]:
stand_bce = - torch.mean(target*torch.log(input_bnl.probs.float()) + (1-target)*torch.log(1-input_bnl.probs.float()))
print(stand_bce)

tensor(1.2529)
