In [1]:
import torch

/opt/conda/envs/ma/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [13]:
x = torch.tensor([1,2,3])
print(x.size())
y1 = x.repeat(4,2)
print(y1.size())

torch.Size([3])
torch.Size([4, 6])


In [14]:
y1

tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])

In [3]:
x.repeat(4, 2, 1).size()

torch.Size([4, 2, 3])

In [4]:
y = x.repeat(4, 2, 1)
print(y)

tensor([[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]])


In [6]:
x = torch.randn(2,3,5).view(-1,10,1)

In [7]:
x.size()

torch.Size([3, 10, 1])

In [8]:
y = x.repeat(1, 1, 4)

In [9]:
y.size()

torch.Size([3, 10, 4])

In [10]:
y

tensor([[[ 0.3485,  0.3485,  0.3485,  0.3485],
         [-0.5944, -0.5944, -0.5944, -0.5944],
         [-0.2237, -0.2237, -0.2237, -0.2237],
         [-0.9032, -0.9032, -0.9032, -0.9032],
         [ 1.3323,  1.3323,  1.3323,  1.3323],
         [ 0.2159,  0.2159,  0.2159,  0.2159],
         [ 0.6991,  0.6991,  0.6991,  0.6991],
         [-1.3273, -1.3273, -1.3273, -1.3273],
         [-0.1115, -0.1115, -0.1115, -0.1115],
         [-0.5315, -0.5315, -0.5315, -0.5315]],

        [[-0.6289, -0.6289, -0.6289, -0.6289],
         [-0.6281, -0.6281, -0.6281, -0.6281],
         [ 3.0472,  3.0472,  3.0472,  3.0472],
         [ 0.6737,  0.6737,  0.6737,  0.6737],
         [ 1.1269,  1.1269,  1.1269,  1.1269],
         [ 0.3032,  0.3032,  0.3032,  0.3032],
         [ 0.6425,  0.6425,  0.6425,  0.6425],
         [ 0.6523,  0.6523,  0.6523,  0.6523],
         [-1.0946, -1.0946, -1.0946, -1.0946],
         [ 1.2246,  1.2246,  1.2246,  1.2246]],

        [[-0.0491, -0.0491, -0.0491, -0.0491],
         

In [11]:
x

tensor([[[ 0.3485],
         [-0.5944],
         [-0.2237],
         [-0.9032],
         [ 1.3323],
         [ 0.2159],
         [ 0.6991],
         [-1.3273],
         [-0.1115],
         [-0.5315]],

        [[-0.6289],
         [-0.6281],
         [ 3.0472],
         [ 0.6737],
         [ 1.1269],
         [ 0.3032],
         [ 0.6425],
         [ 0.6523],
         [-1.0946],
         [ 1.2246]],

        [[-0.0491],
         [-0.5118],
         [ 0.0915],
         [ 0.1223],
         [ 0.5553],
         [ 0.8903],
         [-0.0085],
         [-0.1046],
         [-0.5798],
         [ 0.8407]]])