In [1]:
import torch
import torch.nn as nn

In [2]:
loss = nn.BCEWithLogitsLoss()
input = torch.randn(3, requires_grad=True)
target = torch.empty(3).random_(2)
output = loss(input, target)
output.backward()

In [3]:
print(input)

tensor([ 1.1129, -1.5362, -0.6176], requires_grad=True)


In [4]:
print(target)

tensor([1., 0., 1.])


In [5]:
print(output)

tensor(0.5093, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [6]:
input_sigmoid = torch.sigmoid(input)

In [7]:
print(input_sigmoid)

tensor([0.7527, 0.1771, 0.3503], grad_fn=<SigmoidBackward0>)


In [8]:
from torch.nn import functional as F

In [9]:
output_sigmoid = F.binary_cross_entropy(input_sigmoid, target)

In [10]:
print(output_sigmoid)

tensor(0.5093, grad_fn=<BinaryCrossEntropyBackward0>)


In [11]:
from torch import distributions as dist

In [12]:
input

tensor([ 1.1129, -1.5362, -0.6176], requires_grad=True)

In [13]:
input_bnl = dist.Bernoulli(logits=input)

In [14]:
print(input_bnl.logits)

tensor([ 1.1129, -1.5362, -0.6176], requires_grad=True)


In [15]:
print(input_bnl.probs)

tensor([0.7527, 0.1771, 0.3503], grad_fn=<SigmoidBackward0>)


In [17]:
for i in range(1,5):
    print(i)


1
2
3
4
