In [1]:
import torch

In [4]:
ind = torch.tensor([[0,1,2],[2,1,0],[0,0,0]])
print(ind, ind.size())3290
indX = ind.unsqueeze(-1)
print(indX,indX.size())
indX = indX.expand(-1, -1, 64)
print(indX,indX.size())


tensor([[0, 1, 2],
        [2, 1, 0],
        [0, 0, 0]]) torch.Size([3, 3])
tensor([[[0],
         [1],
         [2]],

        [[2],
         [1],
         [0]],

        [[0],
         [0],
         [0]]]) torch.Size([3, 3, 1])
tensor([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]],

        [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 

In [7]:
partial_points_path = "data/PCN/%s/partial/%s/%s/%02d.pcd"
subset = "train"
dc = "22002"
s = "ddgdfgdfhfgh"
i = 0
path = partial_points_path % (subset, dc, s, i)

In [8]:
print(path)

data/PCN/train/partial/22002/ddgdfgdfhfgh/00.pcd
