In [1]:
import torch
import numpy as np

# Gaussian and MultivariateNormalDiag
Useful resources:
Understanding Shapes in PyTorch Distributions Package https://bochang.me/blog/posts/pytorch-distributions/

In [10]:
mean = torch.tensor([[0,0,0.],[0,0,0.]])
std  = torch.tensor([[1,1,1],[1,1,1.]])
dist = torch.distributions.normal.Normal(mean,std)
# MultivariateNormalDiag
ind  = torch.distributions.independent.Independent(dist, 1)
print(dist.log_prob(mean))
print(ind.log_prob(mean), dist.log_prob(mean).sum(-1))

tensor([[-0.9189, -0.9189, -0.9189],
        [-0.9189, -0.9189, -0.9189]])
tensor([-2.7568, -2.7568]) tensor([-2.7568, -2.7568])


In [11]:
print(dist.mean, dist.variance)
print(ind.mean,  ind.variance )

tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([[1., 1., 1.],
        [1., 1., 1.]])


# Bernoulli

In [28]:
p    = torch.tensor([[0.],[1.],[.5],[.2],[.8]])
dist = torch.distributions.bernoulli.Bernoulli(p)
print('mean/var of dist',dist.mean, dist.variance)
ind  = torch.distributions.independent.Independent(dist, 1)
print('probability:', torch.exp(dist.log_prob(p)), torch.exp(ind.log_prob(p)) )

mean/var of dist tensor([[0.0000],
        [1.0000],
        [0.5000],
        [0.2000],
        [0.8000]]) tensor([[0.0000],
        [0.0000],
        [0.2500],
        [0.1600],
        [0.1600]])
probability: tensor([[1.0000],
        [1.0000],
        [0.5000],
        [0.6063],
        [0.6063]]) tensor([1.0000, 1.0000, 0.5000, 0.6063, 0.6063])


In [35]:
logits    = torch.tensor([[-100.],[10.],[0],[-1],[1]])
dist = torch.distributions.bernoulli.Bernoulli(logits=logits)
print('mean/var of dist',dist.mean, dist.variance)
ind  = torch.distributions.independent.Independent(dist, 1)
print('probability:', torch.exp(dist.log_prob(p)), torch.exp(ind.log_prob(p)) )

mean/var of dist tensor([[0.0000],
        [1.0000],
        [0.5000],
        [0.2689],
        [0.7311]]) tensor([[0.0000e+00],
        [4.5417e-05],
        [2.5000e-01],
        [1.9661e-01],
        [1.9661e-01]])
probability: tensor([[1.0000],
        [1.0000],
        [0.5000],
        [0.5985],
        [0.5985]]) tensor([1.0000, 1.0000, 0.5000, 0.5985, 0.5985])


In [37]:
torch.tensor([1,2,3,4,5,6]).split(3,0)

(tensor([1, 2, 3]), tensor([4, 5, 6]))