In [3]:
import open3d as o3d
import numpy as np

In [11]:
vertices = np.random.rand(10,3)
print(vertices)
trianles = np.random.randint(0,10,size=(20,3))
print(trianles)

[[0.50348543 0.63279785 0.20850751]
 [0.82316423 0.37253508 0.41177949]
 [0.55207128 0.85696691 0.30037101]
 [0.10151875 0.75224569 0.94309483]
 [0.74296292 0.26605337 0.51870945]
 [0.68956341 0.31291012 0.41128918]
 [0.31372412 0.04383282 0.08599986]
 [0.56189541 0.29372123 0.28081159]
 [0.34740664 0.22887141 0.02073454]
 [0.64954262 0.22462563 0.4359648 ]]
[[5 4 2]
 [9 0 0]
 [4 6 2]
 [7 9 0]
 [5 1 2]
 [9 7 3]
 [0 7 6]
 [3 0 0]
 [9 2 9]
 [5 0 5]
 [5 3 7]
 [7 9 5]
 [3 3 9]
 [1 1 0]
 [5 1 5]
 [5 8 6]
 [2 6 8]
 [9 1 5]
 [2 1 8]
 [4 4 4]]


In [13]:
vertices_normal = np.zeros_like(vertices)
print(vertices_normal)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
vertices_tmp = np.random.randint(3,size=(4,3))
print(vertices_tmp)

[[0 2 1]
 [2 0 2]
 [0 0 0]
 [1 1 2]]


In [18]:
vertices_tmp_sum = vertices_tmp.sum(axis=0) / 3
print(vertices_tmp_sum)

[1.         1.         1.66666667]


In [19]:
vertices_normal[1] = vertices_tmp_sum

In [20]:
vertices_normal

array([[0.        , 0.        , 0.        ],
       [1.        , 1.        , 1.66666667],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [21]:
vertices_normal.ptp(axis=0) # Peak to peak

array([1.        , 1.        , 1.66666667])

In [22]:
vertices_tmp.ptp(axis=0)

array([2, 2, 2])