In [1]:
import torch
from torch import nn

/opt/conda/envs/ma/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


3D卷积, 输入的shape是(N, C_in, D_in, H_in, W_in), 输出shape(N, C_out, D_out, H_out, W_out )

<img src="../../pic/Conv3d_Shape.png" style="zoom:100%" />

In [2]:
# Sample intput | 随机输入
net_input = torch.randn(16, 32, 10, 128, 128)

In [3]:
conv3d = nn.Conv3d(32, 64, kernel_size=3, stride=2,padding=1)
net_output = conv3d(net_input)
print(net_output.shape)

torch.Size([32, 64, 5, 64, 64])


In [4]:
net_output.size()

torch.Size([32, 64, 5, 64, 64])

In [13]:

input2 = input.clone()
print(input)
print(input2)

tensor([[[[[ 0.3005,  0.0148,  0.1543],
           [-1.8009,  0.6725, -0.1381]],

          [[ 1.0713,  1.6428,  0.7569],
           [ 1.0697, -1.0883,  1.0084]]],


         [[[-0.6721,  0.8340,  0.1514],
           [ 1.5199,  0.1171,  0.6401]],

          [[-0.5633,  1.2925, -0.0742],
           [-0.5936,  0.7179,  0.5420]]]]])
tensor([[[[[ 0.3005,  0.0148,  0.1543],
           [-1.8009,  0.6725, -0.1381]],

          [[ 1.0713,  1.6428,  0.7569],
           [ 1.0697, -1.0883,  1.0084]]],


         [[[-0.6721,  0.8340,  0.1514],
           [ 1.5199,  0.1171,  0.6401]],

          [[-0.5633,  1.2925, -0.0742],
           [-0.5936,  0.7179,  0.5420]]]]])


In [17]:
conv3d = nn.Conv3d(3,4,1)
conv1d = nn.Conv1d(3,4,1)

In [33]:
input = torch.randn(1,2,2,2,3)
input2 = input.clone()
print(input)
print(input2)
input = input.permute(0,4,1,2,3)

tensor([[[[[-1.7027, -0.7018, -1.7819],
           [ 1.4990,  0.6454,  0.8585]],

          [[ 1.8852, -0.2317,  1.5936],
           [ 0.0828, -0.9938, -1.7343]]],


         [[[ 1.0886, -0.9597, -0.7489],
           [-0.7109,  1.3764,  1.5259]],

          [[-0.0401,  2.0923, -0.4369],
           [-1.3859,  0.5232, -0.2636]]]]])
tensor([[[[[-1.7027, -0.7018, -1.7819],
           [ 1.4990,  0.6454,  0.8585]],

          [[ 1.8852, -0.2317,  1.5936],
           [ 0.0828, -0.9938, -1.7343]]],


         [[[ 1.0886, -0.9597, -0.7489],
           [-0.7109,  1.3764,  1.5259]],

          [[-0.0401,  2.0923, -0.4369],
           [-1.3859,  0.5232, -0.2636]]]]])


In [34]:
output = conv3d(input)
print(output)

tensor([[[[[-0.9346, -0.0482],
           [-0.3428, -1.3088]],

          [[-1.1807,  0.7787],
           [ 0.5401,  0.0029]]],


         [[[ 1.9475, -0.8611],
           [-0.8647,  1.0390]],

          [[ 0.2822, -0.0085],
           [-0.3281,  1.0220]]],


         [[[-0.1827, -0.6189],
           [-0.2272, -0.3829]],

          [[-0.3536, -0.3380],
           [-1.1267, -0.3221]]],


         [[[ 0.6653, -0.0713],
           [ 0.2112, -0.0870]],

          [[-0.1794,  1.0666],
           [-0.1502,  0.8590]]]]], grad_fn=<ConvolutionBackward0>)


In [35]:
print(input2)
input2 =  input2.view(1, 3, 8)
input2.shape

tensor([[[[[-1.7027, -0.7018, -1.7819],
           [ 1.4990,  0.6454,  0.8585]],

          [[ 1.8852, -0.2317,  1.5936],
           [ 0.0828, -0.9938, -1.7343]]],


         [[[ 1.0886, -0.9597, -0.7489],
           [-0.7109,  1.3764,  1.5259]],

          [[-0.0401,  2.0923, -0.4369],
           [-1.3859,  0.5232, -0.2636]]]]])


torch.Size([1, 3, 8])

In [36]:
output2 = conv1d(input2)
print(output2)

tensor([[[ 0.1529, -0.3445, -0.0114, -1.0260,  1.2742,  1.0850,  0.2436,
           0.4153],
         [ 0.2611, -0.5501, -0.6169, -1.6735,  0.3563, -0.3961, -0.8271,
          -0.5039],
         [ 0.6581, -0.5577,  0.4108, -2.7317,  0.3151, -0.1148, -1.6165,
          -0.1086],
         [-0.2271, -0.6047, -1.8661, -0.5849,  0.2266, -0.9305, -0.1121,
          -1.0933]]], grad_fn=<ConvolutionBackward0>)


In [37]:
output2.shape

torch.Size([1, 4, 8])

In [38]:
output2 = output2.view(1,4,2,2,2)

In [32]:
output2

tensor([[[[[ 0.8046,  0.5925],
           [ 0.4942, -0.0249]],

          [[ 0.4426,  1.1667],
           [ 0.3555,  1.0206]]],


         [[[ 0.0758,  0.1085],
           [-0.6287,  0.0072]],

          [[-0.5788,  0.3136],
           [-0.4040,  0.2661]]],


         [[[ 0.0311,  0.0072],
           [-0.2881,  0.5076]],

          [[-0.6462,  0.6835],
           [-0.9457, -0.5513]]],


         [[[-0.0191,  0.1052],
           [-1.1786, -0.5977]],

          [[-0.6653, -0.2630],
           [ 0.0621,  1.0194]]]]], grad_fn=<ViewBackward0>)