In [1]:
import torch
import torch.nn as nn

In [2]:
# FloatTensor containing pretrained weights
weight = torch.FloatTensor([[1, 2.3, 3], [4, 5.1, 6.3]])
print(weight)
embedding = nn.Embedding.from_pretrained(weight)
# Get embeddings for index 1
input = torch.LongTensor([1])
print(input)
embedding(input)

tensor([[1.0000, 2.3000, 3.0000],
        [4.0000, 5.1000, 6.3000]])
tensor([1])


tensor([[4.0000, 5.1000, 6.3000]])

In [7]:
input = torch.LongTensor([1,0,1])
print(input)
embedding(input)

tensor([1, 0, 1])


tensor([[4.0000, 5.1000, 6.3000],
        [1.0000, 2.3000, 3.0000],
        [4.0000, 5.1000, 6.3000]])