In [2]:
import torch
from torch import nn
import numpy as np

In [3]:
X_2dim=np.array([[1,2,3,4],
                 [2,3,45,6]]) #二维数组(2,4)
X_3dim=np.array([[[1,2,3,4],
                  [2,3,4,6],
                  [3,4,5,5]],
                 [[1,1,5,6],
                  [0,0,6,5],
                  [3,3,5,7]]]) # 三维数组（2,3,4）

In [4]:

#转成tensor的形式，因为Linear要求输入是float类型，因此还需要转成float32
X2_tensor=torch.from_numpy(X_2dim.astype(np.float32))
X3_tensor=torch.from_numpy(X_3dim.astype(np.float32))

In [5]:
#用来改变最后数组最后一维的维度
#用来缩小或者扩展特征维度
emdeding=nn.Linear(4,3)
Y2=emdeding(X2_tensor)
Y3=emdeding(X3_tensor)


In [6]:

#输出
print(Y2)
print(Y3)

tensor([[ 1.8309,  0.7600, -0.6563],
        [10.5949,  4.5120, -4.4885]], grad_fn=<AddmmBackward0>)
tensor([[[ 1.8309,  0.7600, -0.6563],
         [ 2.4270,  0.9352, -0.7332],
         [ 2.2396,  0.5981, -0.4975]],

        [[ 2.4502,  1.4058, -1.1235],
         [ 2.5137,  1.5758, -1.3339],
         [ 2.4605,  1.0694, -0.7815]]], grad_fn=<AddBackward0>)


In [7]:
X3_v = X3_tensor.view(-1,4)
Y3_v = emdeding(X3_v)
print(Y3_v)

tensor([[ 1.8309,  0.7600, -0.6563],
        [ 2.4270,  0.9352, -0.7332],
        [ 2.2396,  0.5981, -0.4975],
        [ 2.4502,  1.4058, -1.1235],
        [ 2.5137,  1.5758, -1.3339],
        [ 2.4605,  1.0694, -0.7815]], grad_fn=<AddmmBackward0>)


In [8]:
Y3_v.view(2,3,3)

tensor([[[ 1.8309,  0.7600, -0.6563],
         [ 2.4270,  0.9352, -0.7332],
         [ 2.2396,  0.5981, -0.4975]],

        [[ 2.4502,  1.4058, -1.1235],
         [ 2.5137,  1.5758, -1.3339],
         [ 2.4605,  1.0694, -0.7815]]], grad_fn=<ViewBackward0>)