In [1]:
import numpy as np

In [2]:
a = np.random.randint(0,10,size=[4,3])
b = np.random.randint(0,10,size=[4,3])
print(a)
print(b)

[[6 5 6]
 [2 5 6]
 [1 3 9]
 [6 2 9]]
[[0 2 4]
 [8 6 6]
 [0 3 5]
 [8 7 2]]


In [3]:
a0 = a[0]
b0 = b[0]
print(a0)
print(b0)

[6 5 6]
[0 2 4]


In [4]:
np.cross(a0, b0)

array([  8, -24,  12])

In [5]:
np.cross(a, b)

array([[  8, -24,  12],
       [ -6,  36, -28],
       [-12,  -5,   3],
       [-59,  60,  26]])

In [7]:
a3 = a[3]
b3 = b[3]
print(a3)
print(b3)

[6 2 9]
[8 7 2]


In [8]:
np.cross(a3, b3)

array([-59,  60,  26])