In [1]:
import numpy as np

In [3]:
a = np.random.randint(0,10,size=[2,4,3])
print(a)
a1 = a.reshape(4,2,3)
print(a1)

[[[3 9 6]
  [0 1 0]
  [2 7 7]
  [9 0 2]]

 [[2 0 6]
  [1 9 2]
  [9 6 4]
  [9 3 5]]]
[[[3 9 6]
  [0 1 0]]

 [[2 7 7]
  [9 0 2]]

 [[2 0 6]
  [1 9 2]]

 [[9 6 4]
  [9 3 5]]]
