In [1]:
import numpy as np

In [2]:
a = np.random.randint(0,10,size=[4,3])
b = np.random.randint(0,10,size=[4,3])
print(a)
print(b)

[[7 6 8]
 [7 4 6]
 [0 1 1]
 [2 2 3]]
[[7 5 5]
 [1 8 9]
 [0 6 0]
 [6 3 9]]


In [3]:
c = (a*b)
print(c)

[[49 30 40]
 [ 7 32 54]
 [ 0  6  0]
 [12  6 27]]


In [4]:
c_sum_1 = c.sum(axis=1)
print(c_sum_1)

[119  93   6  45]


array([ True,  True, False, False])