In [1]:
import numpy as np

In [2]:
a = np.random.randint(0,10,size=[2,4,3])
print(a)
a1 = a.transpose(1,0,2)
print(a1)

[[[9 5 9]
  [5 4 9]
  [2 8 4]
  [0 9 6]]

 [[2 6 3]
  [7 5 1]
  [2 8 2]
  [8 1 2]]]
[[[9 5 9]
  [2 6 3]]

 [[5 4 9]
  [7 5 1]]

 [[2 8 4]
  [2 8 2]]

 [[0 9 6]
  [8 1 2]]]
